Added form
zieeco/rails-blog-app pull request #7
Opened 2022-07-15 17:39 UTC by zieeco

**In this milestone I did the following**

- Created forms to perform the following functions:

   - Created a Post on behalf of the current_user.
   - Created a comment on behalf of the current_user.
   - Allowed Users to add likes to Posts.

2022-07-15 18:17 UTC, peterrobert requested changes
Hi @zieeco , 

Very nice project. I love the way you have created a very descriptive readme file 👏🏿 . However, there are a few changes to be made kindly check below ⬇️

### Highlights!

[ ] Good feature branch name ✔️
[ ] Descriptive pull request ✔️

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread or tag me @peterrobert if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-15 18:17 UTC, peterrobert commented on app/controllers/posts_controller.rb
> +    @user = current_user
### [OPTIONAL] 

- [ ] It will be great not to initialize our current user in the new method. The reason is that we arent using the current_user in this method. This will make your code even more cleaner

2022-07-15 18:17 UTC, peterrobert commented on app/views/posts/show.html.erb
> +  <% end %>
- [ ] It will be good to have the comment form in a separate folder. For example `views/comments/new.html.erb file`. This is a good practice and is what is usually expected when creating a rails application. Since all the models have separate folders for the views. Kindly correct this approach

2022-07-15 18:17 UTC, peterrobert commented on app/controllers/likes_controller.rb
> +    )
- [ ] It will be great to actually get the user from the current_user which you have already declared on the application controller. The problem with this approach is that you are getting the user_id from the params. This shouldn't be the case. Kindly check below for a hint: 
```ruby
def create
      @post = Post.find(params[:post_id])
      @like = @current_user.likes.new(post_id: @post.id)

end
```

2022-07-15 18:17 UTC, peterrobert commented on config/routes.rb
> -  resources :users, only: [:index, :show] do
- [ ] It will be great not to nest the user resource in your route. Remember we want to get the current_user from the method we have already created in the application controller, not the parameters. So there is no need to nest all the routes inside a users resource.

2022-07-16 07:34 UTC, zieeco commented on app/controllers/likes_controller.rb
> +    )
- this issue has been resolved :heavy_check_mark:

2022-07-16 11:39 UTC, zieeco commented on config/routes.rb
> -  resources :users, only: [:index, :show] do
- Please, I think you didn't check the wireframe well enough, as they are been nested. see the wireframe [here](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/projects/Views_project.md)

2022-07-16 11:50 UTC, peterrobert commented on config/routes.rb
> -  resources :users, only: [:index, :show] do
Yes they are nested... apologies about this

2022-07-16 12:09 UTC, medaminedev66 approved these changes
Hi @zieeco 😃, 

Your project is complete!  There is nothing else to say other than... it's time to merge it 💯 
Congratulations! 🎉 

### Highlights
- Your web app works well and runs without errors
- Well done with the improvements that the previous reviewer requested.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-16 12:09 UTC, medaminedev66 commented on app/controllers/posts_controller.rb
> +    @user = current_user
[OPTIONAL] In the `new` method, there is no need for the instant variable `@user`.

2022-07-16 12:09 UTC, medaminedev66 commented on app/controllers/comments_controller.rb
> +    @user = User.find_by(id: params[:user_id])
[OPTIONAL] In the new method, there is no need for the instant variable @user.

2022-07-18 14:22 UTC, merged